# adapted from https://docs.github.com/en/actions/quickstart

name: Simple

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  simple-lint-test:
    name: Lint + Test Python
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          make setup
      - name: Lint
        run: |
          make lint
      - name: Test
        run: |
          make test
